-- 规范草案：迁移代码必须通过 $wpdb->prefix 动态生成表名。
-- MariaDB 10.11 / InnoDB / utf8mb4。所有 DATETIME 保存 UTC。
-- 枚举值由应用层受控；DDL 中的 wp_ 仅为展示，迁移不得写死。

CREATE TABLE wp_sr_schema_migrations (
  migration_id VARCHAR(64) NOT NULL,
  checksum CHAR(64) NOT NULL,
  batch_no INT UNSIGNED NOT NULL,
  execution_ms INT UNSIGNED NOT NULL DEFAULT 0,
  applied_at DATETIME NOT NULL,
  PRIMARY KEY (migration_id),
  KEY idx_batch (batch_no, applied_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

CREATE TABLE wp_sr_idempotency_keys (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  scope VARCHAR(64) NOT NULL,
  key_hash CHAR(64) NOT NULL,
  request_hash CHAR(64) NOT NULL,
  actor_type VARCHAR(16) NOT NULL,
  actor_id BIGINT UNSIGNED NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'processing',
  response_code SMALLINT UNSIGNED NULL,
  response_json LONGTEXT NULL,
  resource_type VARCHAR(64) NULL,
  resource_id VARCHAR(64) NULL,
  expires_at DATETIME NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_scope_key (scope, key_hash),
  KEY idx_expiry_status (expires_at, status),
  KEY idx_actor (actor_type, actor_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

CREATE TABLE wp_sr_resource_versions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  resource_id BIGINT UNSIGNED NOT NULL,
  version_label VARCHAR(64) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'draft',
  is_current TINYINT(1) NOT NULL DEFAULT 0,
  storage_provider VARCHAR(24) NULL,
  storage_bucket VARCHAR(128) NULL,
  storage_key VARCHAR(512) NULL,
  original_filename VARCHAR(255) NULL,
  mime_type VARCHAR(128) NULL,
  file_size BIGINT UNSIGNED NULL,
  sha256 CHAR(64) NULL,
  compatibility_json LONGTEXT NULL,
  scan_status VARCHAR(24) NOT NULL DEFAULT 'pending',
  scan_result_json LONGTEXT NULL,
  release_notes LONGTEXT NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  approved_by BIGINT UNSIGNED NULL,
  activated_at DATETIME NULL,
  suspended_at DATETIME NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  KEY idx_resource_status (resource_id, status),
  KEY idx_resource_current (resource_id, is_current),
  KEY idx_sha256 (sha256)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

CREATE TABLE wp_sr_payment_submissions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  submission_key CHAR(36) NOT NULL,
  order_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  state VARCHAR(24) NOT NULL DEFAULT 'submitted',
  channel VARCHAR(32) NOT NULL,
  account_key VARCHAR(64) NULL,
  currency CHAR(3) NOT NULL DEFAULT 'CNY',
  expected_amount DECIMAL(12,2) NOT NULL,
  reported_amount DECIMAL(12,2) NOT NULL,
  reported_paid_at DATETIME NOT NULL,
  payer_note VARCHAR(255) NULL,
  proof_storage_key VARCHAR(512) NOT NULL,
  proof_sha256 CHAR(64) NOT NULL,
  proof_mime_type VARCHAR(128) NOT NULL,
  proof_file_size BIGINT UNSIGNED NOT NULL,
  proof_deleted_at DATETIME NULL,
  external_reference VARCHAR(128) NULL,
  transaction_fingerprint CHAR(64) NULL,
  verified_amount DECIMAL(12,2) NULL,
  verified_paid_at DATETIME NULL,
  approval_idempotency_key_hash CHAR(64) NULL,
  reviewer_id BIGINT UNSIGNED NULL,
  claimed_at DATETIME NULL,
  decision_code VARCHAR(64) NULL,
  internal_note TEXT NULL,
  user_message TEXT NULL,
  lock_version INT UNSIGNED NOT NULL DEFAULT 0,
  submitted_at DATETIME NOT NULL,
  reviewed_at DATETIME NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_submission_key (submission_key),
  UNIQUE KEY uq_transaction_fingerprint (transaction_fingerprint),
  KEY idx_order (order_id),
  KEY idx_order_state (order_id, state),
  KEY idx_user (user_id),
  KEY idx_state_created (state, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

CREATE TABLE wp_sr_entitlements (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  edd_customer_id BIGINT UNSIGNED NULL,
  grant_type VARCHAR(24) NOT NULL,
  source_type VARCHAR(24) NOT NULL,
  source_order_id BIGINT UNSIGNED NULL,
  source_order_item_id BIGINT UNSIGNED NULL,
  plan_download_id BIGINT UNSIGNED NULL,
  parent_entitlement_id BIGINT UNSIGNED NULL,
  resource_id BIGINT UNSIGNED NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'active',
  starts_at DATETIME NOT NULL,
  expires_at DATETIME NULL,
  scope_type VARCHAR(24) NOT NULL,
  scope_snapshot_json LONGTEXT NOT NULL,
  quota_snapshot_json LONGTEXT NULL,
  rules_version VARCHAR(32) NOT NULL,
  priority INT NOT NULL DEFAULT 100,
  created_by BIGINT UNSIGNED NULL,
  revoked_at DATETIME NULL,
  revoked_by BIGINT UNSIGNED NULL,
  revoke_reason VARCHAR(255) NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_source_order_item (source_order_item_id),
  KEY idx_user_active (user_id, status, expires_at),
  KEY idx_order (source_order_id),
  KEY idx_parent (parent_entitlement_id),
  KEY idx_resource (resource_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

CREATE TABLE wp_sr_entitlement_counters (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  entitlement_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  period_type VARCHAR(16) NOT NULL,
  period_key VARCHAR(32) NOT NULL,
  limit_snapshot INT UNSIGNED NOT NULL,
  used_count INT UNSIGNED NOT NULL DEFAULT 0,
  reserved_count INT UNSIGNED NOT NULL DEFAULT 0,
  lock_version INT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_counter_period (entitlement_id, period_type, period_key),
  KEY idx_user_period (user_id, period_type, period_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

CREATE TABLE wp_sr_download_tokens (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  request_id CHAR(36) NOT NULL,
  idempotency_key_hash CHAR(64) NULL,
  request_hash CHAR(64) NULL,
  token_hash CHAR(64) NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  resource_id BIGINT UNSIGNED NOT NULL,
  version_id BIGINT UNSIGNED NOT NULL,
  grant_type VARCHAR(24) NOT NULL,
  grant_id BIGINT UNSIGNED NULL,
  entitlement_id BIGINT UNSIGNED NULL,
  counter_id BIGINT UNSIGNED NULL,
  quota_units INT UNSIGNED NOT NULL DEFAULT 0,
  status VARCHAR(24) NOT NULL DEFAULT 'issued',
  max_uses SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  use_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  expires_at DATETIME NOT NULL,
  consumed_at DATETIME NULL,
  redirected_at DATETIME NULL,
  failure_code VARCHAR(64) NULL,
  ip_hash CHAR(64) NULL,
  ua_hash CHAR(64) NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_request_id (request_id),
  UNIQUE KEY uq_token_hash (token_hash),
  KEY idx_user_status (user_id, status),
  KEY idx_idempotency (idempotency_key_hash),
  KEY idx_expiry_status (expires_at, status),
  KEY idx_resource_version (resource_id, version_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

CREATE TABLE wp_sr_download_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  request_id CHAR(36) NOT NULL,
  token_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  entitlement_id BIGINT UNSIGNED NULL,
  resource_id BIGINT UNSIGNED NOT NULL,
  version_id BIGINT UNSIGNED NOT NULL,
  access_source VARCHAR(24) NOT NULL,
  counted TINYINT(1) NOT NULL DEFAULT 0,
  result VARCHAR(24) NOT NULL,
  error_code VARCHAR(64) NULL,
  bytes_expected BIGINT UNSIGNED NULL,
  ip_hash CHAR(64) NULL,
  ua_hash CHAR(64) NULL,
  started_at DATETIME NOT NULL,
  redirected_at DATETIME NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_event_request (request_id),
  UNIQUE KEY uq_event_token (token_id),
  KEY idx_user_date (user_id, created_at),
  KEY idx_resource_result (resource_id, result, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

CREATE TABLE wp_sr_rights_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  resource_id BIGINT UNSIGNED NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'pending',
  source_type VARCHAR(32) NOT NULL,
  rights_holder VARCHAR(255) NULL,
  license_scope TEXT NULL,
  license_reference VARCHAR(255) NULL,
  evidence_storage_key VARCHAR(512) NULL,
  starts_at DATETIME NULL,
  expires_at DATETIME NULL,
  reviewer_id BIGINT UNSIGNED NULL,
  reviewed_at DATETIME NULL,
  internal_note TEXT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  KEY idx_resource_status (resource_id, status),
  KEY idx_expiry (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

CREATE TABLE wp_sr_favorites (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  resource_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_user_resource (user_id, resource_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

CREATE TABLE wp_sr_support_tickets (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  ticket_no VARCHAR(32) NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  type VARCHAR(32) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'open',
  priority VARCHAR(16) NOT NULL DEFAULT 'normal',
  subject VARCHAR(255) NOT NULL,
  order_id BIGINT UNSIGNED NULL,
  resource_id BIGINT UNSIGNED NULL,
  download_event_id BIGINT UNSIGNED NULL,
  assignee_id BIGINT UNSIGNED NULL,
  first_response_at DATETIME NULL,
  resolved_at DATETIME NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_ticket_no (ticket_no),
  KEY idx_user (user_id),
  KEY idx_status_priority (status, priority, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

CREATE TABLE wp_sr_support_messages (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  ticket_id BIGINT UNSIGNED NOT NULL,
  actor_type VARCHAR(16) NOT NULL,
  actor_id BIGINT UNSIGNED NULL,
  visibility VARCHAR(16) NOT NULL DEFAULT 'customer',
  body LONGTEXT NOT NULL,
  attachment_storage_key VARCHAR(512) NULL,
  created_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  KEY idx_ticket_created (ticket_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

CREATE TABLE wp_sr_audit_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  actor_type VARCHAR(16) NOT NULL,
  actor_id BIGINT UNSIGNED NULL,
  actor_role VARCHAR(64) NULL,
  action VARCHAR(96) NOT NULL,
  object_type VARCHAR(64) NOT NULL,
  object_id VARCHAR(64) NOT NULL,
  before_json LONGTEXT NULL,
  after_json LONGTEXT NULL,
  reason_code VARCHAR(64) NULL,
  note TEXT NULL,
  request_id CHAR(36) NOT NULL,
  idempotency_key VARCHAR(128) NULL,
  ip_hash CHAR(64) NULL,
  ua_hash CHAR(64) NULL,
  created_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  KEY idx_actor (actor_type, actor_id, created_at),
  KEY idx_object (object_type, object_id, created_at),
  KEY idx_action_time (action, created_at),
  KEY idx_request (request_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

CREATE TABLE wp_sr_outbox_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  event_key VARCHAR(128) NOT NULL,
  event_name VARCHAR(96) NOT NULL,
  aggregate_type VARCHAR(64) NOT NULL,
  aggregate_id VARCHAR(64) NOT NULL,
  payload_json LONGTEXT NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'pending',
  attempts SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  available_at DATETIME NOT NULL,
  processed_at DATETIME NULL,
  last_error TEXT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_event_key (event_key),
  KEY idx_status_available (status, available_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
